FROM node:lts-alpine

RUN mkdir -p /app/fractional
# make the 'app' folder the current working directory
WORKDIR /app/fractional

# copy project files and folders to the current working directory (i.e. 'app' folder)
COPY frontend /app/fractional

# install project dependencies
RUN npm install


# build app for production with minification
#RUN npm run build

EXPOSE 5173
#ENTRYPOINT  ["/bin/sleep", "3600"]
ENTRYPOINT  ["/usr/local/bin/npm", "run", "dev"]

