LABEL maintainer="Suchandra Thapa <suchandra.spam+docker@gmail.com>"

FROM ghcr.io/astral-sh/uv:0.8.13-python3.13-alpine AS local-base

RUN apk update

FROM local-base
ENV PYTHONFAULTHANDLER=1 \
    PYTHONUNBUFFERED=1 \
    PYTHONHASHSEED=random \
    PIP_NO_CACHE_DIR=off \
    PIP_DISABLE_PIP_VERSION_CHECK=on \
    PIP_DEFAULT_TIMEOUT=100 \
    UV_COMPILE_BYTECODE=1

RUN mkdir /srv/fastapi
COPY pyproject.toml /srv/fastapi/pyproject.toml
COPY uv.lock /srv/fastapi/uv.lock

# Ensure the installed binary is on the `PATH`
ENV PATH="/root/.local/bin/:$PATH"


COPY /backend/app/* /srv/fastapi
RUN mkdir /srv/fastapi/data
COPY /backend/scripts/players-desc.json /srv/fastapi/data/players.json
WORKDIR /srv/fastapi
RUN  uv sync --frozen --no-install-project



ENTRYPOINT ["/srv/fastapi/.venv/bin/fastapi", "run", "main.py", "--port", "8000", "--host", "0.0.0.0", "--reload"]
#ENTRYPOINT  ["/bin/sleep", "3600"]

